package org.cloudoholiq.catalog.model.pricing;

public enum CurrencyType {
        ALL, USD, AFN, ARS, AWG, AZN, BSD, BBD, BYR, EUR, BZD, BMD, BOB, BAM, BWP, BGN, BRL, GBP, BND, KHR, CAD, KYD, CLP, CNY, COP, CRC, HRK, CUP, CZK, DKK, DOP, XCD, EGP, SVC, FKP, FJD, GHS, GIP, GTQ, GGP, GYD, HNL, HKD, HUF, ISK, INR, IDR, IRR, IMP, ILS, JMD, JEP, KZT, KRW, LAK, LVL, LBP, LRD, CHF, LTL, MKD, MYR, MZN, NAD, NPR, ANG, NZD, NIO, NGN, NOK, OMR, PKR, PAB, PYG, PEN, PHP, PLN, QAR, RON, RUB, SHP, SAR, RSD, SGD, SBD, SOS, ZAR, LKR, SEK, SRD, SYP, THB, TTD, TRY, TVD, UAH, UYU, UZS, VEF, VND, YER, ZWD, AUD, JPY, TWD, MXN, CREDIT,
        AED, AMD, AOA, BDT, BHD, BIF, BOV, BTN, CDF, CLF, CUC, CVE, DJF, DZD, ERN, ETB, GEL, GMD, GNF, HTG, IQD, JOD, KES, KGS, KMF, KPW, KWD, LSL, LYD, MAD, MDL, MGA, MMK, MNT, MOP, MRO, MUR, MVR, MWK, PGK, RWF, SCR, SDG, SLL, SPL, STD, SZL, TJS, TMT, TND, TOP, TZS, UGX, VUV, WST, XAF, XDR, XOF, XPF, ZMK;
}
